### ISSUE TITLE
Tuple Example in Chapter 3

### ISSUE THREAD

**Issue by warrenrross** [ProfessorKazarinoff/Problem-Solving-with-Python#3]
https://github.com/ProfessorKazarinoff/Problem-Solving-with-Python/blob/master/notebooks/03-Data-Types-and-Variables/03.05-Dictionaries-and-Tuples.ipynb

In this workbook, the first example you give for Tuples, the wording right before the example does not match the values in the first example. Later examples do match.

![image](https://user-images.githubusercontent.com/3011009/53596971-dd259f00-3b55-11e9-8dc2-4d50f8b91d9b.png)

**Comment by ProfessorKazarinoff** [comment]
Thanks RandallPark! 

Very easy to follow the issue. By including a link to the notebook, the change was quick and easy. Thanks! Revised text shows:

Tuples are defined in Python by enclosing elements in parenthesis ( ) and separating elements with commas. The command below creates a tuple containing the numbers 3, 4, and 5.

```
>>> t_var = (3,4,5)
>>> t_var
(3, 4, 5)
```

Changes can be seen in [https://problemsolvingwithpython.com/03-Data-Types-and-Variables/03.05-Dictionaries-and-Tuples/#tuples](https://problemsolvingwithpython.com/03-Data-Types-and-Variables/03.05-Dictionaries-and-Tuples/#tuples)

Thanks for making the book better for other readers and learners!  -Peter

**Comment by ProfessorKazarinoff** [comment]
issue closed
