### ISSUE TITLE
wrong answer in section on python REPL, python as calculator.

### ISSUE THREAD

**Issue by ChrisStokes** [ProfessorKazarinoff/Problem-Solving-with-Python#4]
ex reads: 
>>> 5 * 2
2.0

**Comment by ProfessorKazarinoff** [comment]
Thanks ChrisStokes! Edit complete. New text shows:

What is the total mass if we have 2 batteries, and each battery weighs 5 kg?

```
>>> 5 * 2
10
```

Change can be seen online: [https://problemsolvingwithpython.com/02-The-Python-REPL/02.01-Python-as-a-Calculator/#arithmetic](https://problemsolvingwithpython.com/02-The-Python-REPL/02.01-Python-as-a-Calculator/#arithmetic)

Thanks for keeping the book up-to-date and helping other readers and learners!  -Peter

**Comment by ProfessorKazarinoff** [comment]
Issue closed
